<a href="https://colab.research.google.com/github/Shalinib6/numpy_basics/blob/main/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os

# Create a folder
os.makedirs("my_folder", exist_ok=True)

# Save a file in that folder
with open("my_folder/sample.txt", "w") as f:
    f.write("Hello from Colab!")
from google.colab import drive
drive.mount('/content/drive')




Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#linear_algebra in numpy
import numpy as np
#Create two 2×2 matrices and perform matrix multiplication.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(result)
resultt=np.matmul(A,B)
print(resultt)
print(A@B)


#Transpose the following matrix using NumPy:
C= np.array([[1, 2], [3, 4]])
print(np.transpose(C))
print(C.T)

#Find the inverse of matrix
D= np.array([[2, 1], [5, 3]])
print(np.linalg.inv(D))

#Compute the determinant of:
E= np.array([[4, 6], [3, 8]])
print(np.linalg.det(E))

# Eigenvalues / Solve Equations
#Find the eigenvalues and eigenvectors of:
A = np.array([[2, 0], [0, 3]])
eigenvalues,eigenvector=np.linalg.eig(A)
print(eigenvalues)
print(eigenvector)

#Solve the linear equation system:
#2x + y = 8
#3x + 4y = 18
A = np.array([[2, 1], [3, 4]])
b = np.array([8, 18])
x = np.linalg.solve(A, b)
print(x)

#Given a matrix, calculate its trace using NumPy.
F= np.array([[1, 2,3],[4,5,6],[7,8,9]])
print(np.trace(F))

#What will np.linalg.matrix_rank() return for a zero matrix?
G=np.zeros((3,3))
print(np.linalg.matrix_rank(G))

#to find the magnitude of a given matrix
H= np.array([[1, 2], [3, 4]])
print(np.linalg.norm



[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[ 3. -1.]
 [-5.  2.]]
14.000000000000004
[2. 3.]
[[1. 0.]
 [0. 1.]]
[2.8 2.4]
15
0
5.477225575051661
