<a href="https://colab.research.google.com/github/Shalinib6/numpy_basics/blob/main/numpy_package.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os

# Create a folder
os.makedirs("my_folder", exist_ok=True)

# Save a file in that folder
with open("my_folder/sample.txt", "w") as f:
    f.write("Hello from Colab!")


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#How do you create a 1D NumPy array from a Python list?

import numpy as np
c=np.array([1,2,3,4])
print (c)




[1 2 3 4]


In [ ]:
#How do you create a 2D array (matrix) using np.array()
import numpy as np
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#How can you generate an array filled with zeros or ones
import numpy as np
c=np.zeros(5)
print(c)

cp=np.ones(5)
print(cp)

cpp=np.ones((2,3))
print(cpp)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#How do you create an identity matrix
c=np.eye(3,2)
print(c)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [ ]:
#How do you create an array with a range of values (like Python’s range)?
c=np.arange(5)
print(c)
cp=np.arange(2,10,2)
print(cp)
cpp=np.linspace(0,1,4)
print(cpp)

[0 1 2 3 4]
[2 4 6 8]
[0.         0.33333333 0.66666667 1.        ]


In [ ]:
#How do you create a random array of given shape?
import numpy as np
c=np.random.rand(5)
print(c)
cp=np.random.rand(2,3)
print(cp)
cpp=np.random.randn(1000)

[0.98479779 0.34596515 0.1953042  0.77274513 0.62871687]


In [ ]:
# 1D array of 4 random integers from 0 to 9
import numpy as np
d = np.random.randint(0, 10, size=4)
print(d)

# 2x3 array of random integers from 50 to 100
e = np.random.randint(50, 101, size=(2, 3))
print(e)


[8 3 5 0]
[[63 96 70]
 [84 72 98]]


In [4]:
#How do you check the shape (dimensions) of a NumPy array?
import numpy as np
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c.shape)

#How do you find the number of dimensions in an array?
print(c.ndim)

#How do you access elements in a 2D array?
print(c[1,2])

#How can you get the total number of elements in an array?
print(c.size)

#How do you find the data type of elements in an array?
print(c.dtype)
cp=["apple","banana","jackfruit"]
print(np.array(cp).dtype)



(2, 4)
2
7
8
int64
<U9


In [9]:
#How do you access the first, last, or any element in a 1D array?
import numpy as np
c=np.array([1,2,3,4])
print(c[-1])
print(c[-2])
#How do you access rows and columns in a 2D array?
cp=np.array([[1,2,3,4],[5,6,7,8]])
print(cp[-1,-2])

#How do you slice a 2D array to get a submatrix?
cpp=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(cpp[1:, 2:])

#How do you use negative indexing in NumPy arrays
cppp=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(cppp[:,-1])

4
3
7
[[ 7  8]
 [11 12]]
[ 4  8 12]


In [20]:
#How do you add, subtract, multiply, or divide two arrays element-wise?
import numpy as np
c=np.array([1,2,3,4])
cp=np.array([5,6,7,8])
print(c+cp)
print(c-cp)
print(c*cp)
print(c/cp)

#How do you perform power or square operations on arrays?
cpp=np.array([1,2,3,4])
cppp=np.array([5,6,7,8])
print(cpp**cppp)
print(cpp**2)
print(np.square(cpp))
print(np.power(cpp,cppp))
print(np.power(cpp,2))

#How do you calculate the sum, mean, or standard deviation of an array?
cpppp=np.array([1,3,5,6])
print(np.sum(cpppp))
print(np.mean(cpppp))
#How do you perform matrix multiplication using NumPy?
a=np.array([[1,2],[4,5]])
b=np.array([[7,8],[10,11]])
result=np.dot(a,b)
print(result)

#How do you compute the transpose of a matrix?
d=np.array([[1,2,3,4],[6,7,8,9]])
print(d.T)
print(np.transpose(d))
#How do you find the inverse or determinant of a matrix?
e=np.array([[1,2],[3,4]])
print(np.linalg.det(e))
print(np.linalg.inv(e))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]
[ 1  4  9 16]
[ 1  4  9 16]
[    1    64  2187 65536]
[ 1  4  9 16]
15
3.75
[[27 30]
 [78 87]]
[[1 6]
 [2 7]
 [3 8]
 [4 9]]
[[1 6]
 [2 7]
 [3 8]
 [4 9]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [27]:
#How do you reshape a 1D array into a 2D array?
a=np.array([1,2,3,4,5,6])
print(a.reshape(2,3))

#How do you flatten a multidimensional array?
b=np.array([[1,2,3],[4,5,6]])
print(b.flatten())
print(b.ravel())

#How do you concatenate or stack arrays vertically and horizontally?
c=np.array([1,2,3])
d=np.array([4,5,6])
print(np.vstack((c,d)))
print(np.hstack((c,d)))
print(np.stack((c,d)))
print(np.concatenate((c,d)))

#How do you split an array into multiple subarrays?
e=np.array([1,2,3,4,5,6])
print(np.split(e,3))
print(np.array_split(e,3))
f=np.array([1,2,3,4,5])
print(np.array_split(f,3))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5])]


In [6]:
#How do you compare two arrays element-wise (like a > b)
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([[9,2,3,6],[5,7,2,9]])
c=np.array([[1,2,3,4],[5,6,7,8]])
print(a==b)
print(a>b)
print(a<b)
print(np.equal(a,b))
print(np.all(a==b))
print(np.any(a==b))
print(np.all(a==c))


#How do you find elements that satisfy a condition (like a[a > 3])?
print(a[a>3])

#How do you replace values in an array based on a condition?
a[a>2]=9
print(a)


#How do you use np.where() for conditional selection?
print(np.where(a[a>5],30,25))

[[False  True  True False]
 [ True False False False]]
[[False False False False]
 [False False  True False]]
[[ True False False  True]
 [False  True False  True]]
[[False  True  True False]
 [ True False False False]]
False
True
True
[4 5 6 7 8]
[[1 2 9 9]
 [9 9 9 9]]
[30 30 30 30 30 30]


In [11]:
#How do you sort an array?
import numpy as np
a=np.array([1,6,3,9,9,1,3])
sort_a=np.sort(a)
print(sort_a)

#How do you get only the unique values in an array?
print(np.unique(a))

#How do you check if any or all elements of a condition are True?
print(np.all(a>5))
print(np.any(a>5))

#How do you handle NaN (Not a Number) values in arrays?
b=np.array([1,2,3,np.nan,5])
print(b)
print(np.isnan(b))
clear_b=b[~np.isnan(b)]
print(clear_b)


[1 1 3 3 6 9 9]
[1 3 6 9]
False
True
[ 1.  2.  3. nan  5.]
[False False False  True False]
[1. 2. 3. 5.]
