<a href="https://colab.research.google.com/github/Shalinib6/numpy_basics/blob/main/numpy_package.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os

# Create a folder
os.makedirs("my_folder", exist_ok=True)

# Save a file in that folder
with open("my_folder/sample.txt", "w") as f:
    f.write("Hello from Colab!")


In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
#How do you create a 1D NumPy array from a Python list?

import numpy as np
c=np.array([1,2,3,4])
print (c)




[1 2 3 4]


In [6]:
#How do you create a 2D array (matrix) using np.array()
import numpy as np
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
#How can you generate an array filled with zeros or ones
import numpy as np
c=np.zeros(5)
print(c)

cp=np.ones(5)
print(cp)

cpp=np.ones((2,3))
print(cpp)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
#How do you create an identity matrix
c=np.eye(3,2)
print(c)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [14]:
#How do you create an array with a range of values (like Python’s range)?
c=np.arange(5)
print(c)
cp=np.arange(2,10,2)
print(cp)
cpp=np.linspace(0,1,4)
print(cpp)

[0 1 2 3 4]
[2 4 6 8]
[0.         0.33333333 0.66666667 1.        ]


In [15]:
#How do you create a random array of given shape?
import numpy as np
c=np.random.rand(5)
print(c)
cp=np.random.rand(2,3)
print(cp)
cpp=np.random.randn(1000)

[0.98479779 0.34596515 0.1953042  0.77274513 0.62871687]


In [16]:
# 1D array of 4 random integers from 0 to 9
import numpy as np
d = np.random.randint(0, 10, size=4)
print(d)

# 2x3 array of random integers from 50 to 100
e = np.random.randint(50, 101, size=(2, 3))
print(e)


[8 3 5 0]
[[63 96 70]
 [84 72 98]]


In [20]:
#How do you check the shape (dimensions) of a NumPy array?
import numpy as np
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c.shape)

#How do you find the number of dimensions in an array?
print(c.ndim)

#How do you access elements in a 2D array?
print(c[1,2])

#How can you get the total number of elements in an array?
print(c.size)

#How do you find the data type of elements in an array?
print(c.dtype)



(2, 4)
2
7
8
int64
